export const strings = {
  welcomeTo: 'Welcome to',
  brandName: 'OnCare Chat',
  login: 'Login',
  signup: 'Sign Up',
  email: 'Email',
  password: 'Password',
  donotHaveAccount: "Don't have account?",
  alreadyHaveAccount: 'Already have account?',
  firstName: 'First Name',
  lastName: 'Last Name',
  inputRequired: 'Required input',
  invalidEmail: 'Invalid email',
  minPassword: 'Password is too short',
  minName: 'Name is too short',
  maxName: 'Name is too long',
};
