export const strings = {
  welcomeTo: 'Welcome to',
  brandName: 'OnCare Chat',
  login: 'Login',
  signup: 'Sign Up',
  email: 'Email',
  password: 'Password',
  donotHaveAccount: "Don't have account?",
  alreadyHaveAccount: 'Already have account?',
  firstName: 'First Name',
  lastName: 'Last Name',
  inputRequired: 'Required input',
  invalidEmail: 'Invalid email',
  minPassword: 'Password is too short',
  minName: 'Name is too short',
  maxName: 'Name is too long',
  logout: 'Logout',
  errors: {
    unexpected: 'Unexpected error',
    emailAlreadyInUser: 'That email address is already in use!',
    invalidEmail: 'That email address is invalid!',
    existingChatRoom:
      'A chat room exists with this name. Please pick another name',
  },
  settings: 'Settings',
  chat: 'Chat',
  newChat: 'New Chat',
  createNewChat: 'Create New Chat',
  create: 'Create',
  chatRoomName: 'Chat Room Name',
  typeMessage: 'Type message ...',
};
